"""add target_plan_id to payment_transactions

Revision ID: 1f06a0f4b4a6
Revises: 2019cf89921e
Create Date: 2026-08-27 10:17:32.062158

Adds payment_transactions.target_plan_id (spec sections 26-27, 42): the
plan a payment is FOR, distinct from subscription.plan_id for
UPGRADE/DOWNGRADE transactions. Hand-edited from the autogenerated
version to add nullable=True + backfill + NOT NULL, rather than adding
the column as NOT NULL directly, because existing rows (e.g. from prior
smoke-testing) have no value to default to; the backfill sets
target_plan_id = the owning subscription's current plan_id, which is
correct for every payment_type recorded before this migration (only
NEW/RENEWAL existed pre-upgrade/downgrade support).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f06a0f4b4a6'
down_revision: Union[str, None] = '2019cf89921e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('payment_transactions', sa.Column('target_plan_id', sa.Integer(), nullable=True))
    op.execute(
        """
        UPDATE payment_transactions AS pt
        SET target_plan_id = s.plan_id
        FROM subscriptions AS s
        WHERE pt.subscription_id = s.id
          AND pt.target_plan_id IS NULL
        """
    )
    op.alter_column('payment_transactions', 'target_plan_id', nullable=False)
    op.create_index(op.f('ix_payment_transactions_target_plan_id'), 'payment_transactions', ['target_plan_id'], unique=False)
    op.create_foreign_key(None, 'payment_transactions', 'plans', ['target_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_payment_transactions_target_plan_id'), table_name='payment_transactions')
    op.drop_column('payment_transactions', 'target_plan_id')
    # ### end Alembic commands ###
