"""add partial unique index for one active subscription per customer

Revision ID: 2019cf89921e
Revises: 0b418748b9fd
Create Date: 2026-08-27 09:45:28.164558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2019cf89921e'
down_revision: Union[str, None] = '0b418748b9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_one_active_subscription_per_customer_application', 'subscriptions', ['customer_id', 'application_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_active_subscription_per_customer_application', table_name='subscriptions', postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###
