"""
Integration-facing API (spec sections 30-33, 47, 61: /api/v1/integration/) -
server-to-server endpoints Everyticket's OWN backend calls directly,
authenticated with an API key/secret pair, never with an admin bearer
token or a customer OTP session (those authenticate humans; this
authenticates Everyticket's server itself).

2026-09-13 follow-up 3, Vishal's message verbatim: "Test SSO Link -
Actually this has to be generated by Everyticket platform to login into
subscription engine... so need to give API to everyticket Platform to
call that which generates token and return a link so everyticket can use
inside their app. or any other way to make login that customer please
suggest."

Spec section 47 describes Everyticket itself generating the signed SSO
token. In practice that can't be done with just the shared sso_secret,
because this app's replay protection (app.sso.service) is DB-backed: a
token is only ever valid if a matching SsoSession row already exists,
created at the moment the token is minted - so whoever mints the token
must be able to write to this app's database, which only this app can
do. The natural, secure shape is therefore exactly what Vishal asked
for: Everyticket's backend calls this app's API to have the token
minted (this app still owns issuance + the replay-protection row), and
gets back a ready-to-use link.

Auth model, distinct from every other secret already in this app:
  - webhook_secret   signs OUR outbound webhook calls TO Everyticket.
  - sso_secret       (unused by this endpoint) was the original spec's
                     token-signing secret; app.sso.service still signs
                     every token with it internally, but Everyticket
                     never needs to see it now that Everyticket doesn't
                     mint tokens itself.
  - api_credentials  (this module) authenticates Everyticket's INBOUND
                     calls TO this app - an API key/secret pair, set by
                     the admin on the Everyticket Integration config
                     screen (app.api.v1.admin_config) and shared with
                     Everyticket's own team out of band, the same way
                     webhook_secret already is. Sent as X-Api-Key /
                     X-Api-Secret headers, compared with hmac.
                     compare_digest (constant-time - this is a real
                     bearer-credential check, not a convenience
                     equality). Stored in the existing, previously-
                     unused Application.api_credentials JSON column, so
                     no migration was needed for this feature.

This endpoint is deliberately NOT gated by TEST_MODE (unlike the admin
"Generate test SSO link" action, app.api.v1.admin_customers's
/customers/{id}/sso-link) - it's the real production path and must work
in production. Until the admin has actually configured API credentials
here, every call is refused (401), never silently allowed.

Production hardening worth doing on top of this (flagged to Vishal,
not implemented here since it's infrastructure/deployment, not
application code): restrict this endpoint to Everyticket's known
outbound IP range at the reverse proxy/firewall, and require HTTPS end
to end so the API secret and minted tokens are never sent in the clear.
"""
import hmac

from fastapi import APIRouter, Depends, Header, Request
from sqlalchemy.orm import Session

from app.api.deps import get_application, get_db
from app.applications.models import Application, CustomerApplicationMapping
from app.audit import service as audit_service
from app.core.config import get_settings
from app.core.exceptions import CustomerNotFound, Unauthorized
from app.customers.models import Customer
from app.sso import service as sso_service
from app.sso.schemas import SsoLinkGenerateRequest, SsoLinkOut
from datetime import datetime, timedelta, timezone

router = APIRouter(prefix="/integration", tags=["integration"])


def _client_ip(request: Request) -> str | None:
    return request.client.host if request.client else None


def verify_api_credentials(
    application: Application = Depends(get_application),
    x_api_key: str | None = Header(default=None, alias="X-Api-Key"),
    x_api_secret: str | None = Header(default=None, alias="X-Api-Secret"),
) -> Application:
    """Server-to-server auth dependency for this router only - every
    other module in this app authenticates a human (admin bearer token
    or customer OTP session); this authenticates Everyticket's backend
    itself. Refuses (401) if the admin hasn't configured credentials yet,
    if either header is missing, or if either value doesn't match -
    always the same generic message, so a wrong key can't be
    distinguished from a wrong secret or from credentials never having
    been set up at all."""
    creds = application.api_credentials or {}
    expected_key = creds.get("api_key")
    expected_secret = creds.get("api_secret")
    if (
        not expected_key
        or not expected_secret
        or not x_api_key
        or not x_api_secret
        or not hmac.compare_digest(x_api_key, expected_key)
        or not hmac.compare_digest(x_api_secret, expected_secret)
    ):
        raise Unauthorized("Invalid API credentials")
    return application


@router.post("/sso/generate-link", response_model=SsoLinkOut)
def generate_sso_link(
    body: SsoLinkGenerateRequest,
    request: Request,
    db: Session = Depends(get_db),
    application: Application = Depends(verify_api_credentials),
):
    """Real production replacement for the TEST_MODE-only admin action -
    see this module's docstring. Looked up by external_customer_id, which
    (2026-09-14 follow-up: "can we use subscription ID? as we are sending
    to everyticket") is this app's own subscription_id - the same value
    already sent as a fixed field on the subscription.activated webhook
    payload, stored onto CustomerApplicationMapping the moment that
    delivery succeeds (app.webhooks.service._handle_activation_outcome) -
    since by the time a customer clicks "Manage Subscription" inside
    Everyticket's app, the mapping is guaranteed to already exist.
    Everyticket's own app then simply redirects (or opens) the returned
    consume_url - the customer lands signed in, no second password,
    exactly per spec section 47."""
    mapping = (
        db.query(CustomerApplicationMapping)
        .filter(
            CustomerApplicationMapping.application_id == application.id,
            CustomerApplicationMapping.external_customer_id == body.external_customer_id,
        )
        .first()
    )
    if mapping is None:
        raise CustomerNotFound(
            f"No customer is mapped to external_customer_id '{body.external_customer_id}'"
        )

    customer = db.query(Customer).filter(Customer.id == mapping.customer_id).first()
    if customer is None:
        raise CustomerNotFound("Mapped customer no longer exists")

    settings = get_settings()
    token = sso_service.create_sso_token(
        db, application=application, customer=customer, user_identifier=body.user_identifier
    )

    audit_service.record(
        db,
        actor=f"everyticket-integration:{application.code}",
        action="SSO_LINK_GENERATED",
        entity_type="customer",
        entity_id=customer.customer_id,
        new_value={"external_customer_id": body.external_customer_id},
        ip_address=_client_ip(request),
    )
    db.commit()

    expires_at = datetime.now(timezone.utc) + timedelta(seconds=settings.SSO_TOKEN_TTL_SECONDS)
    frontend_url = application.return_url or settings.FRONTEND_URL
    consume_url = f"{frontend_url.rstrip('/')}/sso/consume?token={token}"
    return SsoLinkOut(sso_token=token, consume_url=consume_url, expires_at=expires_at)
