"""
POST /api/v1/integration/sso/generate-link (spec section 47, 2026-09-13
follow-up 3: "Test SSO Link - Actually this has to be generated by
Everyticket platform to login into subscription engine... so need to
give API to everyticket Platform to call that which generates token and
return a link").

This is the real, production, API-key/secret-authenticated replacement
for the TEST_MODE-only admin "Generate test SSO link" action covered by
tests/test_sso.py - both ultimately call the same
app.sso.service.create_sso_token(), so a token minted here is redeemed
through the exact same POST /public/sso/consume, proven end to end below.
"""
from app.applications.models import Application, CustomerApplicationMapping
from app.customers.models import Customer

from tests.test_admin_api import _admin_headers, _new_active_subscription


def _customer_row(db_session, customer_id: str) -> Customer:
    return db_session.query(Customer).filter(Customer.customer_id == customer_id).first()


def _map_to_everyticket(db_session, customer_id: str, external_customer_id: str) -> None:
    application = db_session.query(Application).filter(Application.code == "EVERYTICKET").first()
    customer = _customer_row(db_session, customer_id)
    db_session.add(
        CustomerApplicationMapping(
            customer_id=customer.id, application_id=application.id, external_customer_id=external_customer_id
        )
    )
    db_session.commit()


def _set_api_credentials(db_session, api_key: str, api_secret: str) -> None:
    application = db_session.query(Application).filter(Application.code == "EVERYTICKET").first()
    application.api_credentials = {"api_key": api_key, "api_secret": api_secret}
    db_session.add(application)
    db_session.commit()


def test_generate_sso_link_happy_path_and_token_is_redeemable(client, seeded_db, db_session):
    _new_active_subscription(client, "basic", "integration-sso-happy@example.com", "9800000201")
    headers = _admin_headers(client)
    customer_id = client.get(
        "/api/v1/admin/customers", params={"q": "integration-sso-happy@example.com"}, headers=headers
    ).json()["items"][0]["customer_id"]

    _set_api_credentials(db_session, "et-key", "et-secret")
    _map_to_everyticket(db_session, customer_id, "MUSEUM-9001")

    resp = client.post(
        "/api/v1/integration/sso/generate-link",
        json={"external_customer_id": "MUSEUM-9001", "user_identifier": "everyticket-admin-42"},
        headers={"X-Api-Key": "et-key", "X-Api-Secret": "et-secret"},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["sso_token"]
    assert "/sso/consume?token=" in body["consume_url"]

    consume = client.post("/api/v1/public/sso/consume", json={"token": body["sso_token"]})
    assert consume.status_code == 200, consume.text
    assert consume.json()["customer"]["customer_id"] == customer_id

    from app.audit.models import AuditLog

    entry = (
        db_session.query(AuditLog)
        .filter(AuditLog.action == "SSO_LINK_GENERATED", AuditLog.entity_id == customer_id)
        .first()
    )
    assert entry is not None
    assert entry.actor == "everyticket-integration:EVERYTICKET"


def test_generate_sso_link_refused_when_credentials_not_configured(client, seeded_db, db_session):
    _new_active_subscription(client, "basic", "integration-sso-noconf@example.com", "9800000202")
    headers = _admin_headers(client)
    customer_id = client.get(
        "/api/v1/admin/customers", params={"q": "integration-sso-noconf@example.com"}, headers=headers
    ).json()["items"][0]["customer_id"]
    _map_to_everyticket(db_session, customer_id, "MUSEUM-9002")

    resp = client.post(
        "/api/v1/integration/sso/generate-link",
        json={"external_customer_id": "MUSEUM-9002"},
        headers={"X-Api-Key": "anything", "X-Api-Secret": "anything"},
    )
    assert resp.status_code == 401
    assert resp.json()["error_code"] == "UNAUTHORIZED"


def test_generate_sso_link_rejects_wrong_credentials(client, seeded_db, db_session):
    _new_active_subscription(client, "basic", "integration-sso-wrong@example.com", "9800000203")
    headers = _admin_headers(client)
    customer_id = client.get(
        "/api/v1/admin/customers", params={"q": "integration-sso-wrong@example.com"}, headers=headers
    ).json()["items"][0]["customer_id"]

    _set_api_credentials(db_session, "et-key", "et-secret")
    _map_to_everyticket(db_session, customer_id, "MUSEUM-9003")

    resp = client.post(
        "/api/v1/integration/sso/generate-link",
        json={"external_customer_id": "MUSEUM-9003"},
        headers={"X-Api-Key": "et-key", "X-Api-Secret": "wrong-secret"},
    )
    assert resp.status_code == 401
    assert resp.json()["error_code"] == "UNAUTHORIZED"


def test_generate_sso_link_missing_headers_refused(client, seeded_db, db_session):
    _set_api_credentials(db_session, "et-key", "et-secret")
    resp = client.post(
        "/api/v1/integration/sso/generate-link", json={"external_customer_id": "MUSEUM-DOES-NOT-MATTER"}
    )
    assert resp.status_code == 401
    assert resp.json()["error_code"] == "UNAUTHORIZED"


def test_generate_sso_link_unknown_external_customer_id(client, seeded_db, db_session):
    _set_api_credentials(db_session, "et-key", "et-secret")
    resp = client.post(
        "/api/v1/integration/sso/generate-link",
        json={"external_customer_id": "MUSEUM-NOT-MAPPED"},
        headers={"X-Api-Key": "et-key", "X-Api-Secret": "et-secret"},
    )
    assert resp.status_code == 404
    assert resp.json()["error_code"] == "CUSTOMER_NOT_FOUND"
