"""add notifications_enabled to applications

Revision ID: 2158e8072098
Revises: 2c58d7629015
Create Date: 2026-09-13 16:20:30.264591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2158e8072098'
down_revision: Union[str, None] = '2c58d7629015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default=true (adjusted from the bare autogenerate output) so
    # this NOT NULL column can be added to the existing, already-seeded
    # `applications` table (e.g. EVERYTICKET) without a migration failure -
    # every pre-existing application keeps sending notifications exactly
    # as it does today, matching Application.notifications_enabled's own
    # ORM-level default=True.
    op.add_column(
        'applications',
        sa.Column('notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'notifications_enabled')
    # ### end Alembic commands ###
