"""add webhook field selection to applications

Revision ID: 2f423fa60347
Revises: 2158e8072098
Create Date: 2026-09-14 04:34:21.997681

2026-09-14 follow-up: "allow to configure, more data to be passed for
webhook call like plan details including name, amount, expiry etc.. so if
admin select those parameters then it will be passed to webhook". Stores
the admin's per-event optional-field selection as JSON:
{event_type: [field_name, ...]} - see app.webhooks.field_catalog for the
full catalog of what can be selected per event. Nullable, no server
default needed: NULL/missing key means "no optional fields selected for
that event", i.e. every application's payloads are unchanged from today
until an admin explicitly opts in.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f423fa60347'
down_revision: Union[str, None] = '2158e8072098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('webhook_field_selection', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'webhook_field_selection')
    # ### end Alembic commands ###
