"""add_customer_reference_and_request_body_to_webhooks

Revision ID: 7c8790dc6bcf
Revises: 2f423fa60347
Create Date: 2026-09-14 12:18:12.653227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8790dc6bcf'
down_revision: Union[str, None] = '2f423fa60347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_deliveries', sa.Column('request_body', sa.String(length=4000), nullable=True))
    op.add_column('webhook_events', sa.Column('customer_reference', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'customer_reference')
    op.drop_column('webhook_deliveries', 'request_body')
    # ### end Alembic commands ###
