"""add notification bcc and email retry fields

Revision ID: ed10fff07aa9
Revises: 7c8790dc6bcf
Create Date: 2026-09-21 17:21:53.932508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed10fff07aa9'
down_revision: Union[str, None] = '7c8790dc6bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('notification_bcc_emails', sa.String(length=1000), nullable=True))
    op.add_column('notification_logs', sa.Column('application_id', sa.Integer(), nullable=True))
    op.add_column('notification_logs', sa.Column('context', sa.JSON(), nullable=True))
    op.add_column('notification_logs', sa.Column('bcc', sa.JSON(), nullable=True))
    # server_default='1' (adjusted from the bare autogenerate output) so
    # this NOT NULL column can be added to the existing, already-populated
    # `notification_logs` table without a migration failure - every
    # pre-existing row is treated as having had exactly one (its only)
    # attempt, matching NotificationLog.attempt_count's own ORM-level
    # default=1 - same precedent as 2158e8072098's notifications_enabled.
    op.add_column('notification_logs', sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('notification_logs', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_notification_logs_application_id'), 'notification_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_next_retry_at'), 'notification_logs', ['next_retry_at'], unique=False)
    op.create_foreign_key(None, 'notification_logs', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification_logs', type_='foreignkey')
    op.drop_index(op.f('ix_notification_logs_next_retry_at'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_application_id'), table_name='notification_logs')
    op.drop_column('notification_logs', 'next_retry_at')
    op.drop_column('notification_logs', 'attempt_count')
    op.drop_column('notification_logs', 'bcc')
    op.drop_column('notification_logs', 'context')
    op.drop_column('notification_logs', 'application_id')
    op.drop_column('applications', 'notification_bcc_emails')
    # ### end Alembic commands ###
